development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis:localartfinder.x28flm.ng.0001.usw2.cache.amazonaws.com:6379
  channel_prefix: LocalArtFinder_production
